# Generated by Django 6.0.4 on 2026-04-24 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="عنوان دسته\u200cبندی"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="شناسه (انگلیسی)")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                ("slug", models.SlugField(unique=True, verbose_name="شناسه (انگلیسی)")),
                (
                    "is_new",
                    models.BooleanField(default=False, verbose_name="محصول جدید است؟"),
                ),
                (
                    "old_price",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="قیمت قدیم"
                    ),
                ),
                (
                    "new_price",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="قیمت جدید"
                    ),
                ),
                (
                    "discount",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="درصد تخفیف (مثلا ۲۸٪)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="ExecutedWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        max_length=500, verbose_name="آدرس تصویر نمونه کار"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executed_works",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه کار",
                "verbose_name_plural": "نمونه کارها",
            },
        ),
        migrations.CreateModel(
            name="ProductGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(max_length=500, verbose_name="آدرس تصویر"),
                ),
                (
                    "is_video",
                    models.BooleanField(default=False, verbose_name="آیا ویدیو است؟"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری محصول",
                "verbose_name_plural": "گالری محصولات",
            },
        ),
    ]
