# Generated by Django 6.0.4 on 2026-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executedwork",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="new_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="productgallery",
            name="image_url",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="تصویر دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="executedwork",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/executed/",
                verbose_name="آپلود تصویر نمونه کار",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/main/",
                verbose_name="تصویر اصلی",
            ),
        ),
        migrations.AddField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/gallery/",
                verbose_name="آپلود تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="درصد تخفیف (مثلاً ۲۸٪)",
            ),
        ),
    ]
