# Generated by Django 6.0.4 on 2026-04-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_executedwork_image_url_remove_product_is_new_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام پشتیبان")),
                (
                    "telegram_id",
                    models.CharField(
                        help_text="مثلاً: admin_support",
                        max_length=100,
                        verbose_name="آی\u200cدی بله یا شماره تماس",
                    ),
                ),
            ],
            options={
                "verbose_name": "پشتیبان",
                "verbose_name_plural": "پشتیبان\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="web_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="لینک محصول در وب\u200cاپ (سایت)"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان دسته"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="تخفیف (مثلاً ۱۰٪)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(default="1", upload_to="products/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="support_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.supportcontact",
                verbose_name="پشتیبان اختصاصی",
            ),
        ),
    ]
